let students=Array.isArray(window.ITI_DATA)?JSON.parse(JSON.stringify(window.ITI_DATA)):[];let baseData=JSON.parse(JSON.stringify(students));let filtered=[];let selected=new Set();const photos=new Map();const $=id=>document.getElementById(id);
function key(v){return String(v??"").toLowerCase().trim().replace(/\.[a-z0-9]{2,5}$/,"").replace(/[^a-z0-9]+/g,"")}
function val(s,k){return s[k]??""}
function label(s){return `${val(s,"name")||"Unnamed"} — ${val(s,"enrol")||""}`}
function photo(s){let c=[val(s,"enrol"),val(s,"name"),val(s,"roll")].map(key).filter(Boolean);for(const x of c)if(photos.has(x))return photos.get(x);for(const [n,u]of photos)if(c.some(x=>n.includes(x)||x.includes(n)))return u;return val(s,"photo")}
function card(s){let p=photo(s);return `<div class="card-top"><div class="logo">ITI</div><div><h2>SHREE S K PATEL ITI KADI</h2><div class="sub">GIA-509 · S V CAMPUS KADI</div><div class="title">TRAINEE IDENTITY CARD</div></div></div><div class="photo-area"><div class="photo">${p?`<img src="${p}">`:"PHOTO"}</div></div><div class="details">${row("Name",s.name)}${row("Enrollment No.",s.enrol)}${row("Roll No.",s.roll||"—")}${row("Trade",s.trade)}${row("Batch / Session",`${s.batch||""} / ${s.session||""}`)}${row("DOB",s.dob)}${row("Address",s.address)}</div><div class="signatures"><span>Student Signature</span><span>Principal</span></div><div class="footer">If found, please return to the institute.</div>`}
function row(a,b){return `<div class="row"><span>${a}</span><b>${String(b??"—")||"—"}</b></div>`}
function show(s){if(s)$("idCard").innerHTML=card(s)}
function update(){let q=$("search").value.toLowerCase().trim(),t=$("tradeFilter").value;filtered=students.filter(s=>(!q||Object.values(s).join(" ").toLowerCase().includes(q))&&(!t||s.trade===t));let sel=$("studentSelect");sel.innerHTML=filtered.map(s=>`<option value="${s._index}">${label(s)}</option>`).join("");if(filtered[0])show(filtered[0]);let list=$("studentList");list.innerHTML=filtered.map(s=>`<label class="student-item"><input type="checkbox" data-i="${s._index}" ${selected.has(s._index)?"checked":""}>${label(s)}</label>`).join("");list.querySelectorAll("input").forEach(x=>x.onchange=()=>{let i=+x.dataset.i;x.checked?selected.add(i):selected.delete(i);updateCount()});$("count").textContent=`${filtered.length} students · ${selected.size} selected`;updateCount()}
function updateCount(){$("count").textContent=`${filtered.length} students · ${selected.size} selected`;$("selectAll").checked=filtered.length>0&&filtered.every(s=>selected.has(s._index))}
function rebuildTrades(){let ts=[...new Set(students.map(s=>s.trade).filter(Boolean))].sort();$("tradeFilter").innerHTML='<option value="">All trades</option>'+ts.map(t=>`<option>${t}</option>`).join("")}
function chosen(){let a=[...selected].map(i=>students[i]).filter(Boolean);if(a.length)return a;let i=+$("studentSelect").value;return Number.isNaN(i)?[]:[students[i]]}
function print(arr){$("printArea").className="print-area grid";$("printArea").innerHTML=arr.map(s=>`<article class="id-card">${card(s)}</article>`).join("");window.print()}
async function pdf(arr,name){$("printArea").className="print-area grid";$("printArea").innerHTML=arr.map(s=>`<article class="id-card">${card(s)}</article>`).join("");await html2pdf().set({margin:5,filename:name,image:{type:"jpeg",quality:.95},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:"mm",format:"a4",orientation:"portrait"}}).from($("printArea")).save();$("printArea").innerHTML=""}
$("excelFile").onchange=e=>{let f=e.target.files[0],r=new FileReader();r.onload=x=>{let wb=XLSX.read(x.target.result,{type:"array"}),a=[];wb.SheetNames.forEach(sn=>XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:""}).forEach((r,i)=>a.push({sr:r["Sr. No."]||r.SR||i+1,enrol:r.EnrolmentNo||r.EnrollmentNo||r["Enrollment No."]||r.enrollment||"",session:r.Session||r.session||"",trade:r.Trade||r.trade||"",batch:r.Batch||r.batch||"",name:r["Student Name"]||r.Name||r.name||"",dob:r["Date of Birth"]||r.DOB||r.dob||"",address:r.Address||r.address||"",roll:r["Roll No."]||r.rollno||r.RollNo||""}));students=a.map((s,i)=>({...s,_index:i}));selected.clear();localStorage.setItem("itiData",JSON.stringify(students));$("dbStatus").textContent="Excel data loaded and saved on this browser.";rebuildTrades();update()};r.readAsArrayBuffer(f)}
$("photoFiles").onchange=e=>{photos.clear();[...e.target.files].forEach(f=>photos.set(key(f.name),URL.createObjectURL(f)));update();$("status").textContent=`${e.target.files.length} photo(s) loaded. Match by enrollment/name/roll in filename.`}
$("search").oninput=update;$("tradeFilter").onchange=update;$("studentSelect").onchange=e=>show(students[+e.target.value]);$("selectAll").onchange=e=>{filtered.forEach(s=>e.target.checked?selected.add(s._index):selected.delete(s._index));update()}
$("previewBtn").onclick=()=>show(students[+$("studentSelect").value]);$("printBtn").onclick=()=>print(chosen());$("bulkBtn").onclick=()=>print(chosen());$("pdfBtn").onclick=()=>pdf(chosen(),"ITI_ID_Cards_Selected.pdf");$("allPdfBtn").onclick=()=>pdf(filtered,"ITI_ID_Cards_All.pdf");
$("saveDb").onclick=()=>{localStorage.setItem("itiData",JSON.stringify(students));$("status").textContent="Current Excel data saved in this browser."}
$("resetDb").onclick=()=>{localStorage.removeItem("itiData");location.reload()}
(function(){let saved=localStorage.getItem("itiData");if(saved){try{students=JSON.parse(saved);students.forEach((s,i)=>s._index=i);$("dbStatus").textContent="Using your saved Excel data on this browser."}catch(e){}}students.forEach((s,i)=>s._index=i);rebuildTrades();update();$("status").textContent=`Permanent database loaded: ${students.length} students.`})()
